config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/profile'
  get 'dashboard/search'
  get 'dashboard/settings'
  get 'dashboard/support'
  get 'dashboard/notifications'
  get 'dashboard/news'
  get 'dashboard/evaluation'
  
  get 'dashboard' => 'dashboard#index'
  get 'profile' => 'dashboard#profile'
  get 'profile/:id' => 'dashboard#profile'
  get 'settings' => 'dashboard#settings'
  get 'support' => 'dashboard#support'
  get 'notifications' => 'dashboard#notifications'
  get 'search' => 'dashboard#search'
  get 'news' => 'dashboard#news'
  get 'dashboard/evaluation' => 'dashboard#evaluation'
  get 'sorry' => 'dashboard#support'
  
  get 'newsletters' => 'newsletters#new'

  root 'pages#index'
  
  get 'contact' => 'contacts#new'
  get 'about' => 'pages#about'
  get 'tags/:tag', to: 'posts#index', as: :tag
  
  devise_for :users
  
  resources :newsletters, only: [:new, :create]
  resources :contacts, only: [:new, :create]
  resources :posts
end

app/views/pages/about.html.erb
    <% provide(:title, 'About') %>
    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">About
                </h1>
                <ol class="breadcrumb">
                    <li><i class="fa fa-home"></i><%= link_to 'Home', root_path %>
                    </li>
                    <li class="active"><i class="fa fa-info-circle"></i> About</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Intro Content -->
        <div class="row">
            <div class="col-md-6">
              <%= image_tag 'smartups', :class => 'img-responsive' %>
            </div>
            <div class="col-md-6">
                <h2>What is Smartups?</h2>
                <p>Smartups is a web platform where people can find collaborators to team up with on new exciting ventures.</p>
                <p>The inspiration was clear: many individuals nowadays have great ideas in mind that could turn into long-term projects or even profitable businesses. However, it is quite common that they face difficulties in finding the right partners in order for their dreams to come true. </p>
                <p>We are developing a platform that is simple, straightforward and easy-to-use by people from all backgrounds. It is our belief that we are going to pioneer the way startuppers are connected to each other. </p>
				<p>Sign-up for our <%= link_to 'newsletter', new_newsletter_path %> to get updated about our progress.</p>
            </div>
        </div>
        <!-- /.row -->

        <!-- Team Members -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Our Team</h2>
            </div>
            <div class="col-md-4 text-center">
                <div class="thumbnail">
                    <%= image_tag 'giannis', :class => 'img-responsive' %>
                    <div class="caption">
                        <h3>Giannis Konstantinidis<br>
                            <small>Project Lead</small>
                        </h3>
                        <p>Making sure the project guidelines are met and that everything goes smoothly.</p>
                        <ul class="list-inline">
                            <li><a href="https://www.facebook.com/giannisk95"><i class="fa fa-2x fa-facebook-square"></i></a>
                            </li>
                            <li><a href="https://gr.linkedin.com/in/giannisk"><i class="fa fa-2x fa-linkedin-square"></i></a>
                            </li>
                            <li><a href="https://twitter.com/gianniskon"><i class="fa fa-2x fa-twitter-square"></i></a>
                            </li>
                            <li><a href="mailto:giannis@smartups.io"><i class="fa fa-2x fa-envelope-square"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-4 text-center">
                <div class="thumbnail">
                    <%= image_tag 'christos', :class => 'img-responsive' %>
                    <div class="caption">
                        <h3>Christos Sotirelis<br>
                            <small>Technical Lead</small>
                        </h3>
                        <p>The man running point on the platform and the one to blame when something doesn't work.</p>
                        <ul class="list-inline">
                            <li><a href="https://www.facebook.com/sotirelisc"><i class="fa fa-2x fa-facebook-square"></i></a>
                            </li>
                            <li><a href="https://gr.linkedin.com/in/sotirelisc"><i class="fa fa-2x fa-linkedin-square"></i></a>
                            </li>
                            <li><a href="https://twitter.com/sotirelisc"><i class="fa fa-2x fa-twitter-square"></i></a>
                            </li>
                            <li><a href="mailto:christos@smartups.io"><i class="fa fa-2x fa-envelope-square"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-4 text-center">
                <div class="thumbnail">
                    <%= image_tag 'zacharias', :class => 'img-responsive' %>
                    <div class="caption">
                        <h3>Zacharias Mitzelos<br>
                            <small>Backend Developer</small>
                        </h3>
                        <p>Responsible for pretty much everything running behind the scenes.</p>
                        <ul class="list-inline">
                            <li><a href="https://www.facebook.com/zacharias.mitzelos"><i class="fa fa-2x fa-facebook-square"></i></a>
                            </li>
                            <li><a href="https://gr.linkedin.com/in/zmitzelos"><i class="fa fa-2x fa-linkedin-square"></i></a>
                            </li>
                            <li><a href="https://twitter.com/zmitzie"><i class="fa fa-2x fa-twitter-square"></i></a>
                            </li>
                            <li><a href="mailto:zacharias@smartups.io"><i class="fa fa-2x fa-envelope-square"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->

        <!-- As Seen On -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">As Seen On</h2>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <%= image_tag 'ert1', :class => 'img-responsive customer-img' %>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <%= image_tag 'aegeanstartups', :class => 'img-responsive customer-img' %>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <%= image_tag 'foititikanea', :class => 'img-responsive customer-img' %>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6">
                <%= image_tag 'neolaiagr', :class => 'img-responsive customer-img' %>
            </div>
        </div>
        <!-- /.row -->

app/views/pages/contact.html.erb
    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Contact
                </h1>
                <ol class="breadcrumb">
                    <li><i class="fa fa-home"></i><%= link_to 'Home', root_path %>
                    </li>
                    <li class="active"><i class="fa fa-envelope"></i> Contact</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Content Row -->
        <div class="row">
            <!-- Map Column -->
						<div class="col-md-7">
                <%= image_tag 'contact-us', :class => 'img-responsive' %>
            </div>
            <!-- Contact Details Column -->
            <div class="col-md-4">
                <h3>Contact Details</h3>
                <p>
                    University of the Aegean<br> Dept. of Information & Communication Systems Engineering<br>
										Information Systems Lab<br>Palama 8, Neo Karlovassi<br>83200 Samos Island, Greece
                </p>
                <p><i class="fa fa-phone"></i> 
                    <abbr title="Phone">P</abbr>: (+30) 22730-7890</p>
                <p><i class="fa fa-envelope-o"></i> 
                    <abbr title="Email">E</abbr>: <a href="mailto:contact@smartups.io">contact@smartups.io</a>
                </p>
                <p><i class="fa fa-clock-o"></i> 
                    <abbr title="Hours">H</abbr>: Monday - Friday: 9:00 AM to 5:00 PM</p>
                <ul class="list-unstyled list-inline list-social-icons">
                    <li>
                        <a href="https://facebook.com/smartupsio/"><i class="fa fa-facebook-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-linkedin-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="https://twitter.com/smartupsio"><i class="fa fa-twitter-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-google-plus-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-youtube-square fa-2x"></i></a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /.row -->

        <!-- Contact Form -->
        <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
        <div class="row">
            <div class="col-md-7">
                <h3>Send Us A Message</h3>
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Full Name:</label>
                            <input type="text" class="form-control" id="name" required data-validation-required-message="Please enter your name.">
                            <p class="help-block"></p>
                        </div>
                    </div>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Phone Number:</label>
                            <input type="tel" class="form-control" id="phone" required data-validation-required-message="Please enter your phone number.">
                        </div>
                    </div>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Email Address:</label>
                            <input type="email" class="form-control" id="email" required data-validation-required-message="Please enter your email address.">
                        </div>
                    </div>
                    <div class="control-group form-group">
                        <div class="controls">
                            <label>Message:</label>
                            <textarea rows="10" cols="100" class="form-control" id="message" required data-validation-required-message="Please enter your message" maxlength="999" style="resize:none"></textarea>
                        </div>
                    </div>
                    <div id="success"></div>
										<div class="alert alert-success">
											<strong>Success!</strong> Indicates a successful or positive action.
										</div>
										<div class="alert alert-danger">
											<strong>Danger!</strong> Indicates a dangerous or potentially negative action.
										</div>
                    <!-- For success/fail messages -->
                    <button type="submit" class="btn btn-primary">Send Message</button>
                </form>
            </div>

        </div>
        <!-- /.row -->

app/views/pages/index.html.erb
<div class="container">

        <!-- Jumbotron Header -->
        <header class="jumbotron jumbo-spacer">
            <h1>Welcome to <span class="smartups-logo-bg">smartups</span>.</h1>
            <p>Our mission is to amplify the way startuppers and doers are connected. Whether you are looking for business partners, or ways to scale up your venture, we have the right resources for you.</p>
						<p>As we are coming close to our initial launch, make sure to sign up for our newsletter and keep youself updated. It only takes a minute.</p>

            <%= link_to new_newsletter_path, :class => 'btn btn-primary btn-lg' do %>
               Sign up for our newsletter
            <% end %>
                  
                  
        </header>

        <!-- How It Works Section -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">How It Works</h2>
            </div>
            <div class="col-md-4 col-sm-6">
              <%= image_tag '01sign-up', :class => 'img-responsive img-portfolio img-hover' %>
            </div>
            <div class="col-md-4 col-sm-6">
              <%= image_tag '02confirm-email', :class => 'img-responsive img-portfolio img-hover' %>
            </div>
            <div class="col-md-4 col-sm-6">
              <%= image_tag '03user-profile', :class => 'img-responsive img-portfolio img-hover' %>
            </div>
            <div class="col-md-4 col-sm-6">
              <%= image_tag '04create-smartup', :class => 'img-responsive img-portfolio img-hover' %>
            </div>
            <div class="col-md-4 col-sm-6">
              <%= image_tag '05join-smartup', :class => 'img-responsive img-portfolio img-hover' %>
            </div>
            <div class="col-md-4 col-sm-6">
              <%= image_tag '06collaborate', :class => 'img-responsive img-portfolio img-hover' %>
            </div>
        </div>
        <!-- /.row -->

        <!-- Features Section -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">What To Expect</h2>
            </div>
            <div class="col-md-6">
                <p>We have set out to develop a state of the art, fully responsive, yet simple-to-use web platform for you to take advantage of.</p>
								<p>Here is what you can expect from our very first pre-alpha release:</p>
                <ul>
                    <li>Cross-Device Web Platform.</li>
                    <li>User Profiles w/ Short CV.</li>
                    <li>Evaluate Your Idea.</li>
                    <li>Register Your Smartup.</li>
                    <li>Join Existing Ones.</li>
                </ul>
								<p>Here is what functionality you can expect in the near future:</p>
                <ul>
                    <li>Integrate Social Media Accounts.</li>
                    <li>Find Business Mentors.</li>
                    <li>Locate Incubators.</li>
                    <li>Get Funded.</li>
                    <li>Plus Many More.</li>
                </ul>
                <p>Our team is making some huge progress day by day.</p>
            </div>
            <div class="col-md-6">
	          		<div class="thumbnail">
               			<%= image_tag 'code', :class => 'img-responsive' %>
								</div>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Call to Action Section -->
        <div class="well">
            <div class="row">
                <div class="col-md-8">
                    <p>The development process of Smartups is still ongoing. Subscribe to our newsletter and keep yourself updated with the latest news around our project. Remember: it takes only a minute.</p>
                </div>
                <div class="col-md-4">
                  <%= link_to new_newsletter_path, :class => 'btn btn-lg btn-default btn-block' do %>
                    <i class="fa fa-fw fa-paper-plane"></i> Newsletter
                  <% end %>
                </div>
            </div>
        </div>