config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/profile'
  get 'dashboard/search'
  get 'dashboard/settings'
  get 'dashboard/support'
  get 'dashboard/notifications'
  get 'dashboard/news'
  get 'dashboard/evaluation'
  
  get 'dashboard' => 'dashboard#index'
  get 'profile' => 'dashboard#profile'
  get 'profile/:id' => 'dashboard#profile'
  get 'settings' => 'dashboard#settings'
  get 'support' => 'dashboard#support'
  get 'notifications' => 'dashboard#notifications'
  get 'search' => 'dashboard#search'
  get 'news' => 'dashboard#news'
  get 'dashboard/evaluation' => 'dashboard#evaluation'
  get 'sorry' => 'dashboard#support'
  
  get 'newsletters' => 'newsletters#new'

  root 'pages#index'
  
  get 'contact' => 'contacts#new'
  get 'about' => 'pages#about'
  get 'tags/:tag', to: 'posts#index', as: :tag
  
  devise_for :users
  
  resources :newsletters, only: [:new, :create]
  resources :contacts, only: [:new, :create]
  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  # Uploader for Smartup Post image.
  mount_uploader :post_image, PostImageUploader
  
  # Tags instead of looking_for.
  acts_as_taggable_on :skills
  
  # Smartup Post relations and settings.
  belongs_to :user
  has_many :interests
  has_many :users, through: :interests
  
  # Smartup Post validations.
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 32 }
  validates :content, presence: true, length: { maximum: 512 }
  # Skip skills field validation when seeding.
  validates :skills, presence: true, unless: :skip_skills_validation
  # validates :looking_for, presence: true, length: { maximum: 64 }
  validate :image_size
  
  attr_accessor :skip_skills_validation
  
  default_scope -> { order(created_at: :desc) }
  
  private

    # Validates the size of an uploaded picture.
    def image_size
      if post_image.size > 2.megabytes
        errors.add(:post_image, "should be less than 2MB")
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  before_action :correct_user, only: :destroy

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
  end

  def new
    @post = Post.new
  end
  
  def create
    # For some reason we have to provide again the current user's id.
    @post = current_user.posts.new(post_params.merge(:user_id => current_user.id))
    if @post.save
      flash[:success] = "Successfully created \"#{@post.title}\"!"
      redirect_to action: "index"
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Smartup has been deleted!"
    redirect_to request.referrer || root_url
  end

  private

    def post_params
      params.require(:post).permit(:title, :content, :skill_list)
    end
    
    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this Smartup from being published</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :skill_list, "Add some tags" %><br>
    <%= f.text_field :skill_list %>
  </div>
  <div class="actions">
    <%= f.submit "Post" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<center>
<div id="tag_cloud">
  <% tag_cloud Post.skill_counts, %w[xs s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

<div id="posts">
  <% if @posts.empty? %>
    No Smartup posts found!
  <% end %>
  <% @posts.each do |post| %>
    <h2><%= post.title %></h2>
    Tags: <%= raw post.skill_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
  <% end %>
</div>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
</center>

app/views/posts/new.html.erb
<center>
    <h1>Create a Smartup</h1>
    Lorem Ipsum
    <br /><%= render 'form' %>
</center>