config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/profile'
  get 'dashboard/search'
  get 'dashboard/settings'
  get 'dashboard/support'
  get 'dashboard/notifications'
  get 'dashboard/news'
  get 'dashboard/evaluation'
  
  get 'dashboard' => 'dashboard#index'
  get 'profile' => 'dashboard#profile'
  get 'profile/:id' => 'dashboard#profile'
  get 'settings' => 'dashboard#settings'
  get 'support' => 'dashboard#support'
  get 'notifications' => 'dashboard#notifications'
  get 'search' => 'dashboard#search'
  get 'news' => 'dashboard#news'
  get 'dashboard/evaluation' => 'dashboard#evaluation'
  get 'sorry' => 'dashboard#support'
  
  get 'newsletters' => 'newsletters#new'

  root 'pages#index'
  
  get 'contact' => 'contacts#new'
  get 'about' => 'pages#about'
  get 'tags/:tag', to: 'posts#index', as: :tag
  
  devise_for :users
  
  resources :newsletters, only: [:new, :create]
  resources :contacts, only: [:new, :create]
  resources :posts
end

app/views/layouts/_footer.html.erb
        <hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Smartups 2015</p>
                </div>
            </div>
        </footer>
    </div>
    <!-- Script to Activate the Carousel -->
    <script>
        $('.carousel').carousel({
            interval: 5000 // Changes speed
        })
    </script>

app/views/layouts/_header.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to 'smartups', root_path, :class => 'navbar-brand' %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                      <%= link_to 'About', about_path %>
                    </li>
                    <li>
                      <%= link_to 'Contact', contact_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <link rel="stylesheet" href="/assets/bootstrap.css">
    <link rel="stylesheet" href="/assets/sb-admin.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <div id="wrapper">
      <!-- Navigation -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <%= link_to 'smartups', dashboard_path, :class => 'navbar-brand' %>
      </div>
      <!-- Top Menu Items -->
      <ul class="nav navbar-right top-nav">
        <!-- User Menu Start --> 
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.full_name %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to profile_path do %>
                <i class="fa fa-fw fa-user"></i> Profile
              <% end %>
            </li>
            <li>
              <%= link_to settings_path do %>
                <i class="fa fa-fw fa-gear"></i> Settings
              <% end %>
            </li>
            <li class="divider"></li>
              <li>
              <%= link_to destroy_user_session_path, :method => :delete do %>
                <i class="fa fa-fw fa-power-off"></i> Log Out
              <% end %>
            </li>
          </ul>
        </li>
    		<!-- User Menu End --> 
        </ul>
        <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">
            <li class="active">
              <%= link_to dashboard_path do %>
                <i class="fa fa-fw fa-dashboard"></i> Dashboard
              <% end %>
            </li>
            <li>
              <%= link_to search_path do %>
                <i class="fa fa-fw fa-search"></i> Search Smartups
              <% end %>
            </li>
            <li>
              <a href="javascript:;" data-toggle="collapse" data-target="#gotanidea"><i class="fa fa-fw fa-lightbulb-o"></i> Got An Idea?<i class="fa fa-fw fa-caret-down"></i></a>
              <ul id="gotanidea" class="collapse">
      					<li>
                  <a href="#"><i class="fa fa-fw fa-calculator"></i> Evaluate It</a>
                </li>
      					<li>
      					  <a href="partners.html"><i class="fa fa-fw fa-users"></i> Search For Partners</a>
      			    </li>
        		    <li>
        			    <a href="incubators.html"><i class="fa fa-fw fa-map-marker"></i> Locate Incubators</a>
        	      </li>
                <li>
    	            <a href="mentors.html"><i class="fa fa-fw fa-thumbs-o-up"></i> Find Mentors</a>
    				    </li>
    				    <li>
    				      <a href="funding.html"><i class="fa fa-fw fa-money"></i> Get Funded</a>
    			      </li>
              </ul>
            </li>
    	    <li>
    	      <a href="javascript:;" data-toggle="collapse" data-target="#toolkit"><i class="fa fa-fw fa-wrench"></i> Toolkit <i class="fa fa-fw fa-caret-down"></i></a>
    	       <ul id="toolkit" class="collapse">
    	   <li>
    			 <%= link_to notifications_path do %>
    			   <i class="fa fa-fw fa-bell-o"></i> Notifications
    			 <% end %>
    		</li>
    		<li>
    		    <%= link_to news_path do %>
    		      <i class="fa fa-fw fa-newspaper-o"></i> News
    		    <% end %>
    		</li>
    		<li>
    			 <%= link_to support_path do %>
    			   <i class="fa fa-fw fa-life-ring"></i> Support
    			 <% end %>
    		</li>
    	   </ul>
    	  </li>
       </ul>
      </div>
      <!-- /.navbar-collapse -->
      </nav>
    <%= yield %>
    <hr>
  	<footer>
  		<div class="row">
  			<div class="col-lg-12">
  			  <p>Copyright &copy; Smartups 2015</p>
  			</div>
  	  </div>
  	</footer>
  </body>
</html>